image: nginx:latest

stages:
  - build-image
  - deploy
  
docker build:
  stage: build-image
  script:
  - docker build --rm -t paredros-creator-server-nodb .
  - docker images -a
  tags:
  - deploy

deploy:
  stage: deploy
  script: 
  - docker stop paredros
  - docker run --name paredros -d --rm -p 80:80 paredros-creator-server-nodb
  tags:
  - deploy