image: nginx:latest

stages:
  - build-image
  - deploy
  
build-staging:
  stage: build-image
  script:
  - docker build --rm -t paredros-creator-server-nodb Dockerfile_staging
  - docker images -a
  only:
  - master
  tags:
  - deploy

build-prod:
  stage: build-image
  script:
  - docker build --rm -t paredros-creator-server-nodb Dockerfile_prod
  - docker images -a
  only:
  - release
  tags:
  - deploy

deploy-staging:
  stage: deploy
  script:
  - docker stop paredros-creator-server
  - docker run --name paredros-creator-server --network paredros-net --rm -d -p 1337:80 paredros-creator-server-nodb
  only:
  - master
  tags:
  - deploy

deploy-prod:
  stage: deploy
  script:
  - docker stop paredros-creator-server
  - docker run --name paredros-creator-server --network paredros-net --rm -d -p 80:80 paredros-creator-server-nodb
  only:
  - release
  tags:
  - deploy