image: nginx:latest

stages:
  - build-image
  - deploy
  
docker build:
  stage: build-image
  script:
  - docker build --rm -t paredros-creator-server-nodb .
  - docker images -a
  tags:
  - deploy

deploy:
  stage: deploy
  script:
  - docker network disconnect paredros-net paredros-creator-server 
  - docker stop paredros-creator-server
  - docker run --name paredros-creator-server --network paredros-net --ip 192.168.0.3 --rm -d -p 80:80 paredros-creator-server-nodb
  tags:
  - deploy